#
# Site settings
title: The Quiz
email: samuel@swalladge.id.au
description: > # this means to ignore newlines until "baseurl:"
  Quiz webapp!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://quiz.swalladge.id.au" # the base hostname & protocol for your site

# Build settings
markdown: kramdown


exclude:
  - 'node_modules'
  - 'bower.json'
  - 'README.md'
  - 'Gruntfile.js'
  - 'package.json'
  - 'CNAME'
  - 'tags'
  - 'build_and_deploy.sh'

